name: Publish Docker image

on:
  push:
    branches: ['master']
  pull_request:

jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      # üîç SonarCloud Scan (NON-BLOCKING)
      - name: SonarCloud Scan & Quality Gate
        uses: SonarSource/sonarcloud-github-action@v2
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          entryPoint: bash
          args: >
            -c "
            sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORG }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.qualitygate.wait=true
            "



      # üîê Docker Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # üì¶ Build & Push SINGLE IMAGE
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_IMAGE }}:prod

      
      - name: Debug image name
        run: |
          echo "IMAGE=${{ secrets.DOCKER_IMAGE }}:prod"

